# Generated by Django 5.1.6 on 2025-07-20 20:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OTPRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15)),
                ("otp_code", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("is_verified", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="is_mobile_verified",
            field=models.BooleanField(default=False),
        ),
    ]
