# Generated by Django 5.1.6 on 2025-07-04 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
    ]
