# Generated by Django 5.1.6 on 2025-04-10 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productcategory_product_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='size_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_categories', to='product.sizecategory'),
        ),
    ]
